name: test workflow

on:
  repository_dispatch:
    events:
      [ release_event ]

jobs:
  package:
    runs-on: ubuntu-latest
    name: Create artifacts
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Latest xml2md-input
      id: xml2md-input-release
      run: |
          GET_LATEST_OUTPUT=$(./get_latest.sh ${{ github.repository_owner }} xml2md-input Release.zip xml2md-input)
          echo "GLO: ${GET_LATEST_OUTPUT}"
          RELEASE_VERSION=$(echo $GET_LATEST_OUTPUT | sed 's/Release version: //')
          echo "RELEASE_VERSION: ${RELEASE_VERSION}"
          echo ::set-output name=xml2md-input-version::${RELEASE_VERSION}
    - name: Get Latest excel2xml-input
      id: excel2xml-release
      run: |
          GET_LATEST_OUTPUT=$(./get_latest.sh ${{ github.repository_owner }} excel2xml grupoetra.zip grupoetra)
          echo "GLO: ${GET_LATEST_OUTPUT}"
          RELEASE_VERSION=$(echo $GET_LATEST_OUTPUT | sed 's/Release version: //')
          echo "RELEASE_VERSION: ${RELEASE_VERSION}"
          echo ::set-output name=excel2xml-version::${RELEASE_VERSION}
    - name: Create MD
      id:   build-it-now
      uses: ./
    - name: Create Archive
      id: create-archive
      run: |
        zip -r Bridge Bridge
    - name: Check Vars
      run: |
          echo ${{ steps.xml2md-input-release.output.xml2md-input-version }}
          echo ${{ steps.excel2xml-release.output.excel2xml-version }}
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.tag }}
        release_name: Release ${{ github.event.client_payload.tag }}
        body: "Contains:\nxml2md-input release: ${{ steps.xml2md-input-release.output.xml2md-input-version }}\nexcel2xml release: ${{ steps.excel2xml-release.output.excel2xml-version }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./Bridge.zip
        asset_name: Bridge.zip
        asset_content_type: application/zip
    - uses: juztcode/repo-ditpatch-action@v1
      with:
        event-type: release_event
        token: ${{ secrets.REPO_TRIGGER_KEY }}
        repository: "${{ github.repository_owner }}/github_pages"
        client-payload: '{"tag": "${{ github.event.client_payload.tag }}" }'
