name: test workflow

on:
  repository_dispatch:
    events:
      [ test_event ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Create artifacts
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Create MD
      id:   build-it-now
      uses: ./
    - name: UploadRelease
      uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: ${{ github.workspace }}/output/*.md
